<a href="https://colab.research.google.com/github/JoshuaBarsky/Math-152/blob/main/Classwork_3_7_23.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np
from PIL import Image

In [29]:
from google.colab import files


In [30]:
files.download('dots.png')

FileNotFoundError: ignored

In [31]:
pixels = np.random.choice([True, False], (300,300))

In [32]:
pixels.dtype

dtype('bool')

In [33]:
pixels.shape

(300, 300)

In [34]:
pixels[:10,:10]

array([[False,  True, False, False,  True, False, False,  True,  True,
        False],
       [False,  True, False, False,  True, False,  True,  True, False,
        False],
       [ True,  True,  True,  True, False,  True, False,  True, False,
        False],
       [ True,  True,  True,  True, False,  True,  True,  True, False,
         True],
       [False, False, False,  True, False,  True, False,  True,  True,
        False],
       [False,  True, False,  True,  True, False,  True, False, False,
         True],
       [ True,  True,  True, False,  True, False,  True,  True,  True,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True, False,
        False],
       [False, False,  True,  True,  True, False, False,  True,  True,
         True],
       [ True, False,  True, False,  True,  True, False, False,  True,
        False]])

In [20]:
x = np.arange(0,5)
y = np.arange(0,5)

In [23]:
xy = np.add.outer(x**2, y**2) #makes an addition table

In [24]:
print(xy)

[[ 0  1  4  9 16]
 [ 1  2  5 10 17]
 [ 4  5  8 13 20]
 [ 9 10 13 18 25]
 [16 17 20 25 32]]


In [6]:
x_array = np.arange(-50,51)
y_array = np.arange(-50,51)

In [7]:
xy_array = np.add.outer(x_array**2, y_array**2)

In [16]:
print(xy_array)

[[5000 4901 4804 ... 4804 4901 5000]
 [4901 4802 4705 ... 4705 4802 4901]
 [4804 4705 4608 ... 4608 4705 4804]
 ...
 [4804 4705 4608 ... 4608 4705 4804]
 [4901 4802 4705 ... 4705 4802 4901]
 [5000 4901 4804 ... 4804 4901 5000]]


In [8]:
type(xy_array)

numpy.ndarray

In [11]:
np.size(xy_array)

10201

In [25]:
circ_array = (xy_array <= 2500)

In [26]:
circ_array.shape

(101, 101)

SyntaxError: ignored